---
meta:
  environment: firehose-connectors-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: just_install_packages
    networks:
      - name: firehose_connectors1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: firehose_connectors1
  type: manual
  subnets:
  - range: 10.244.214.0/24
    name: firehose_connectors1
    gateway: 10.244.214.1
    static:
      - 10.244.214.2 - 10.244.214.60
